name: Build and publish release

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Joshua-Ashton/arch-mingw-github-action@v8
      - name: Rustup add windows target
        run: rustup target add x86_64-pc-windows-gnu
      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-pc-windows-gnu/sync-lethal-mods.exe
          asset_name: sync-lethal-mods.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "New release for version ${{ github.ref }}"
